[build]
  kill_delay = "10s"
  delay = 500
  exclude_dir = ["public", "tmp", "vendor", "node_modules"]

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
 
[proxy]
  enabled = true
  proxy_port = 8081
  app_port = 8080
