// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"believer/movies/db"
	"believer/movies/types"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGenreQuerier creates a new instance of MockGenreQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenreQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenreQuerier {
	mock := &MockGenreQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenreQuerier is an autogenerated mock type for the GenreQuerier type
type MockGenreQuerier struct {
	mock.Mock
}

type MockGenreQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenreQuerier) EXPECT() *MockGenreQuerier_Expecter {
	return &MockGenreQuerier_Expecter{mock: &_m.Mock}
}

// GetGenreMovies provides a mock function for the type MockGenreQuerier
func (_mock *MockGenreQuerier) GetGenreMovies(id string, userID string, offset int) (types.Movies, error) {
	ret := _mock.Called(id, userID, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetGenreMovies")
	}

	var r0 types.Movies
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int) (types.Movies, error)); ok {
		return returnFunc(id, userID, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int) types.Movies); ok {
		r0 = returnFunc(id, userID, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Movies)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = returnFunc(id, userID, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreQuerier_GetGenreMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGenreMovies'
type MockGenreQuerier_GetGenreMovies_Call struct {
	*mock.Call
}

// GetGenreMovies is a helper method to define mock.On call
//   - id string
//   - userID string
//   - offset int
func (_e *MockGenreQuerier_Expecter) GetGenreMovies(id interface{}, userID interface{}, offset interface{}) *MockGenreQuerier_GetGenreMovies_Call {
	return &MockGenreQuerier_GetGenreMovies_Call{Call: _e.mock.On("GetGenreMovies", id, userID, offset)}
}

func (_c *MockGenreQuerier_GetGenreMovies_Call) Run(run func(id string, userID string, offset int)) *MockGenreQuerier_GetGenreMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenreQuerier_GetGenreMovies_Call) Return(movies types.Movies, err error) *MockGenreQuerier_GetGenreMovies_Call {
	_c.Call.Return(movies, err)
	return _c
}

func (_c *MockGenreQuerier_GetGenreMovies_Call) RunAndReturn(run func(id string, userID string, offset int) (types.Movies, error)) *MockGenreQuerier_GetGenreMovies_Call {
	_c.Call.Return(run)
	return _c
}

// GetGenreName provides a mock function for the type MockGenreQuerier
func (_mock *MockGenreQuerier) GetGenreName(id string) (db.TableName, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetGenreName")
	}

	var r0 db.TableName
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (db.TableName, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) db.TableName); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(db.TableName)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreQuerier_GetGenreName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGenreName'
type MockGenreQuerier_GetGenreName_Call struct {
	*mock.Call
}

// GetGenreName is a helper method to define mock.On call
//   - id string
func (_e *MockGenreQuerier_Expecter) GetGenreName(id interface{}) *MockGenreQuerier_GetGenreName_Call {
	return &MockGenreQuerier_GetGenreName_Call{Call: _e.mock.On("GetGenreName", id)}
}

func (_c *MockGenreQuerier_GetGenreName_Call) Run(run func(id string)) *MockGenreQuerier_GetGenreName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenreQuerier_GetGenreName_Call) Return(tableName db.TableName, err error) *MockGenreQuerier_GetGenreName_Call {
	_c.Call.Return(tableName, err)
	return _c
}

func (_c *MockGenreQuerier_GetGenreName_Call) RunAndReturn(run func(id string) (db.TableName, error)) *MockGenreQuerier_GetGenreName_Call {
	_c.Call.Return(run)
	return _c
}

// GetGenreStats provides a mock function for the type MockGenreQuerier
func (_mock *MockGenreQuerier) GetGenreStats(userID string, year string) ([]types.ListItem, error) {
	ret := _mock.Called(userID, year)

	if len(ret) == 0 {
		panic("no return value specified for GetGenreStats")
	}

	var r0 []types.ListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]types.ListItem, error)); ok {
		return returnFunc(userID, year)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []types.ListItem); ok {
		r0 = returnFunc(userID, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, year)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreQuerier_GetGenreStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGenreStats'
type MockGenreQuerier_GetGenreStats_Call struct {
	*mock.Call
}

// GetGenreStats is a helper method to define mock.On call
//   - userID string
//   - year string
func (_e *MockGenreQuerier_Expecter) GetGenreStats(userID interface{}, year interface{}) *MockGenreQuerier_GetGenreStats_Call {
	return &MockGenreQuerier_GetGenreStats_Call{Call: _e.mock.On("GetGenreStats", userID, year)}
}

func (_c *MockGenreQuerier_GetGenreStats_Call) Run(run func(userID string, year string)) *MockGenreQuerier_GetGenreStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenreQuerier_GetGenreStats_Call) Return(listItems []types.ListItem, err error) *MockGenreQuerier_GetGenreStats_Call {
	_c.Call.Return(listItems, err)
	return _c
}

func (_c *MockGenreQuerier_GetGenreStats_Call) RunAndReturn(run func(userID string, year string) ([]types.ListItem, error)) *MockGenreQuerier_GetGenreStats_Call {
	_c.Call.Return(run)
	return _c
}

// ListGenres provides a mock function for the type MockGenreQuerier
func (_mock *MockGenreQuerier) ListGenres() ([]db.Genre, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListGenres")
	}

	var r0 []db.Genre
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]db.Genre, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []db.Genre); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Genre)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreQuerier_ListGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGenres'
type MockGenreQuerier_ListGenres_Call struct {
	*mock.Call
}

// ListGenres is a helper method to define mock.On call
func (_e *MockGenreQuerier_Expecter) ListGenres() *MockGenreQuerier_ListGenres_Call {
	return &MockGenreQuerier_ListGenres_Call{Call: _e.mock.On("ListGenres")}
}

func (_c *MockGenreQuerier_ListGenres_Call) Run(run func()) *MockGenreQuerier_ListGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGenreQuerier_ListGenres_Call) Return(genres []db.Genre, err error) *MockGenreQuerier_ListGenres_Call {
	_c.Call.Return(genres, err)
	return _c
}

func (_c *MockGenreQuerier_ListGenres_Call) RunAndReturn(run func() ([]db.Genre, error)) *MockGenreQuerier_ListGenres_Call {
	_c.Call.Return(run)
	return _c
}
