// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"believer/movies/db"
	"believer/movies/types"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLanguageQuerier creates a new instance of MockLanguageQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLanguageQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLanguageQuerier {
	mock := &MockLanguageQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLanguageQuerier is an autogenerated mock type for the LanguageQuerier type
type MockLanguageQuerier struct {
	mock.Mock
}

type MockLanguageQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLanguageQuerier) EXPECT() *MockLanguageQuerier_Expecter {
	return &MockLanguageQuerier_Expecter{mock: &_m.Mock}
}

// GetLanguageMovies provides a mock function for the type MockLanguageQuerier
func (_mock *MockLanguageQuerier) GetLanguageMovies(id string, userID string, offset int) (types.Movies, error) {
	ret := _mock.Called(id, userID, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLanguageMovies")
	}

	var r0 types.Movies
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int) (types.Movies, error)); ok {
		return returnFunc(id, userID, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int) types.Movies); ok {
		r0 = returnFunc(id, userID, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Movies)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = returnFunc(id, userID, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLanguageQuerier_GetLanguageMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLanguageMovies'
type MockLanguageQuerier_GetLanguageMovies_Call struct {
	*mock.Call
}

// GetLanguageMovies is a helper method to define mock.On call
//   - id string
//   - userID string
//   - offset int
func (_e *MockLanguageQuerier_Expecter) GetLanguageMovies(id interface{}, userID interface{}, offset interface{}) *MockLanguageQuerier_GetLanguageMovies_Call {
	return &MockLanguageQuerier_GetLanguageMovies_Call{Call: _e.mock.On("GetLanguageMovies", id, userID, offset)}
}

func (_c *MockLanguageQuerier_GetLanguageMovies_Call) Run(run func(id string, userID string, offset int)) *MockLanguageQuerier_GetLanguageMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLanguageQuerier_GetLanguageMovies_Call) Return(movies types.Movies, err error) *MockLanguageQuerier_GetLanguageMovies_Call {
	_c.Call.Return(movies, err)
	return _c
}

func (_c *MockLanguageQuerier_GetLanguageMovies_Call) RunAndReturn(run func(id string, userID string, offset int) (types.Movies, error)) *MockLanguageQuerier_GetLanguageMovies_Call {
	_c.Call.Return(run)
	return _c
}

// GetLanguageName provides a mock function for the type MockLanguageQuerier
func (_mock *MockLanguageQuerier) GetLanguageName(id string) (db.TableName, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetLanguageName")
	}

	var r0 db.TableName
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (db.TableName, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) db.TableName); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(db.TableName)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLanguageQuerier_GetLanguageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLanguageName'
type MockLanguageQuerier_GetLanguageName_Call struct {
	*mock.Call
}

// GetLanguageName is a helper method to define mock.On call
//   - id string
func (_e *MockLanguageQuerier_Expecter) GetLanguageName(id interface{}) *MockLanguageQuerier_GetLanguageName_Call {
	return &MockLanguageQuerier_GetLanguageName_Call{Call: _e.mock.On("GetLanguageName", id)}
}

func (_c *MockLanguageQuerier_GetLanguageName_Call) Run(run func(id string)) *MockLanguageQuerier_GetLanguageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLanguageQuerier_GetLanguageName_Call) Return(tableName db.TableName, err error) *MockLanguageQuerier_GetLanguageName_Call {
	_c.Call.Return(tableName, err)
	return _c
}

func (_c *MockLanguageQuerier_GetLanguageName_Call) RunAndReturn(run func(id string) (db.TableName, error)) *MockLanguageQuerier_GetLanguageName_Call {
	_c.Call.Return(run)
	return _c
}

// GetLanguageStats provides a mock function for the type MockLanguageQuerier
func (_mock *MockLanguageQuerier) GetLanguageStats(userID string, year string) ([]types.ListItem, error) {
	ret := _mock.Called(userID, year)

	if len(ret) == 0 {
		panic("no return value specified for GetLanguageStats")
	}

	var r0 []types.ListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]types.ListItem, error)); ok {
		return returnFunc(userID, year)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []types.ListItem); ok {
		r0 = returnFunc(userID, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, year)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLanguageQuerier_GetLanguageStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLanguageStats'
type MockLanguageQuerier_GetLanguageStats_Call struct {
	*mock.Call
}

// GetLanguageStats is a helper method to define mock.On call
//   - userID string
//   - year string
func (_e *MockLanguageQuerier_Expecter) GetLanguageStats(userID interface{}, year interface{}) *MockLanguageQuerier_GetLanguageStats_Call {
	return &MockLanguageQuerier_GetLanguageStats_Call{Call: _e.mock.On("GetLanguageStats", userID, year)}
}

func (_c *MockLanguageQuerier_GetLanguageStats_Call) Run(run func(userID string, year string)) *MockLanguageQuerier_GetLanguageStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLanguageQuerier_GetLanguageStats_Call) Return(listItems []types.ListItem, err error) *MockLanguageQuerier_GetLanguageStats_Call {
	_c.Call.Return(listItems, err)
	return _c
}

func (_c *MockLanguageQuerier_GetLanguageStats_Call) RunAndReturn(run func(userID string, year string) ([]types.ListItem, error)) *MockLanguageQuerier_GetLanguageStats_Call {
	_c.Call.Return(run)
	return _c
}

// ListLanguages provides a mock function for the type MockLanguageQuerier
func (_mock *MockLanguageQuerier) ListLanguages() ([]db.Language, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListLanguages")
	}

	var r0 []db.Language
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]db.Language, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []db.Language); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Language)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLanguageQuerier_ListLanguages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLanguages'
type MockLanguageQuerier_ListLanguages_Call struct {
	*mock.Call
}

// ListLanguages is a helper method to define mock.On call
func (_e *MockLanguageQuerier_Expecter) ListLanguages() *MockLanguageQuerier_ListLanguages_Call {
	return &MockLanguageQuerier_ListLanguages_Call{Call: _e.mock.On("ListLanguages")}
}

func (_c *MockLanguageQuerier_ListLanguages_Call) Run(run func()) *MockLanguageQuerier_ListLanguages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLanguageQuerier_ListLanguages_Call) Return(languages []db.Language, err error) *MockLanguageQuerier_ListLanguages_Call {
	_c.Call.Return(languages, err)
	return _c
}

func (_c *MockLanguageQuerier_ListLanguages_Call) RunAndReturn(run func() ([]db.Language, error)) *MockLanguageQuerier_ListLanguages_Call {
	_c.Call.Return(run)
	return _c
}
