// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"believer/movies/db"
	"believer/movies/types"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProductionCountryQuerier creates a new instance of MockProductionCountryQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductionCountryQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductionCountryQuerier {
	mock := &MockProductionCountryQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductionCountryQuerier is an autogenerated mock type for the ProductionCountryQuerier type
type MockProductionCountryQuerier struct {
	mock.Mock
}

type MockProductionCountryQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductionCountryQuerier) EXPECT() *MockProductionCountryQuerier_Expecter {
	return &MockProductionCountryQuerier_Expecter{mock: &_m.Mock}
}

// GetProductionCountryMovies provides a mock function for the type MockProductionCountryQuerier
func (_mock *MockProductionCountryQuerier) GetProductionCountryMovies(id string, userID string, offset int) (types.Movies, error) {
	ret := _mock.Called(id, userID, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetProductionCountryMovies")
	}

	var r0 types.Movies
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int) (types.Movies, error)); ok {
		return returnFunc(id, userID, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int) types.Movies); ok {
		r0 = returnFunc(id, userID, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Movies)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = returnFunc(id, userID, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductionCountryQuerier_GetProductionCountryMovies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionCountryMovies'
type MockProductionCountryQuerier_GetProductionCountryMovies_Call struct {
	*mock.Call
}

// GetProductionCountryMovies is a helper method to define mock.On call
//   - id string
//   - userID string
//   - offset int
func (_e *MockProductionCountryQuerier_Expecter) GetProductionCountryMovies(id interface{}, userID interface{}, offset interface{}) *MockProductionCountryQuerier_GetProductionCountryMovies_Call {
	return &MockProductionCountryQuerier_GetProductionCountryMovies_Call{Call: _e.mock.On("GetProductionCountryMovies", id, userID, offset)}
}

func (_c *MockProductionCountryQuerier_GetProductionCountryMovies_Call) Run(run func(id string, userID string, offset int)) *MockProductionCountryQuerier_GetProductionCountryMovies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProductionCountryQuerier_GetProductionCountryMovies_Call) Return(movies types.Movies, err error) *MockProductionCountryQuerier_GetProductionCountryMovies_Call {
	_c.Call.Return(movies, err)
	return _c
}

func (_c *MockProductionCountryQuerier_GetProductionCountryMovies_Call) RunAndReturn(run func(id string, userID string, offset int) (types.Movies, error)) *MockProductionCountryQuerier_GetProductionCountryMovies_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductionCountryName provides a mock function for the type MockProductionCountryQuerier
func (_mock *MockProductionCountryQuerier) GetProductionCountryName(id string) (db.TableName, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductionCountryName")
	}

	var r0 db.TableName
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (db.TableName, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) db.TableName); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(db.TableName)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductionCountryQuerier_GetProductionCountryName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionCountryName'
type MockProductionCountryQuerier_GetProductionCountryName_Call struct {
	*mock.Call
}

// GetProductionCountryName is a helper method to define mock.On call
//   - id string
func (_e *MockProductionCountryQuerier_Expecter) GetProductionCountryName(id interface{}) *MockProductionCountryQuerier_GetProductionCountryName_Call {
	return &MockProductionCountryQuerier_GetProductionCountryName_Call{Call: _e.mock.On("GetProductionCountryName", id)}
}

func (_c *MockProductionCountryQuerier_GetProductionCountryName_Call) Run(run func(id string)) *MockProductionCountryQuerier_GetProductionCountryName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductionCountryQuerier_GetProductionCountryName_Call) Return(tableName db.TableName, err error) *MockProductionCountryQuerier_GetProductionCountryName_Call {
	_c.Call.Return(tableName, err)
	return _c
}

func (_c *MockProductionCountryQuerier_GetProductionCountryName_Call) RunAndReturn(run func(id string) (db.TableName, error)) *MockProductionCountryQuerier_GetProductionCountryName_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductionCountryStats provides a mock function for the type MockProductionCountryQuerier
func (_mock *MockProductionCountryQuerier) GetProductionCountryStats(userID string, year string) ([]types.ListItem, error) {
	ret := _mock.Called(userID, year)

	if len(ret) == 0 {
		panic("no return value specified for GetProductionCountryStats")
	}

	var r0 []types.ListItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]types.ListItem, error)); ok {
		return returnFunc(userID, year)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []types.ListItem); ok {
		r0 = returnFunc(userID, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.ListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, year)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductionCountryQuerier_GetProductionCountryStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionCountryStats'
type MockProductionCountryQuerier_GetProductionCountryStats_Call struct {
	*mock.Call
}

// GetProductionCountryStats is a helper method to define mock.On call
//   - userID string
//   - year string
func (_e *MockProductionCountryQuerier_Expecter) GetProductionCountryStats(userID interface{}, year interface{}) *MockProductionCountryQuerier_GetProductionCountryStats_Call {
	return &MockProductionCountryQuerier_GetProductionCountryStats_Call{Call: _e.mock.On("GetProductionCountryStats", userID, year)}
}

func (_c *MockProductionCountryQuerier_GetProductionCountryStats_Call) Run(run func(userID string, year string)) *MockProductionCountryQuerier_GetProductionCountryStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductionCountryQuerier_GetProductionCountryStats_Call) Return(listItems []types.ListItem, err error) *MockProductionCountryQuerier_GetProductionCountryStats_Call {
	_c.Call.Return(listItems, err)
	return _c
}

func (_c *MockProductionCountryQuerier_GetProductionCountryStats_Call) RunAndReturn(run func(userID string, year string) ([]types.ListItem, error)) *MockProductionCountryQuerier_GetProductionCountryStats_Call {
	_c.Call.Return(run)
	return _c
}

// ListProductionCountries provides a mock function for the type MockProductionCountryQuerier
func (_mock *MockProductionCountryQuerier) ListProductionCountries() ([]db.ProductionCountry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListProductionCountries")
	}

	var r0 []db.ProductionCountry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]db.ProductionCountry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []db.ProductionCountry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ProductionCountry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductionCountryQuerier_ListProductionCountries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProductionCountries'
type MockProductionCountryQuerier_ListProductionCountries_Call struct {
	*mock.Call
}

// ListProductionCountries is a helper method to define mock.On call
func (_e *MockProductionCountryQuerier_Expecter) ListProductionCountries() *MockProductionCountryQuerier_ListProductionCountries_Call {
	return &MockProductionCountryQuerier_ListProductionCountries_Call{Call: _e.mock.On("ListProductionCountries")}
}

func (_c *MockProductionCountryQuerier_ListProductionCountries_Call) Run(run func()) *MockProductionCountryQuerier_ListProductionCountries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProductionCountryQuerier_ListProductionCountries_Call) Return(productionCountrys []db.ProductionCountry, err error) *MockProductionCountryQuerier_ListProductionCountries_Call {
	_c.Call.Return(productionCountrys, err)
	return _c
}

func (_c *MockProductionCountryQuerier_ListProductionCountries_Call) RunAndReturn(run func() ([]db.ProductionCountry, error)) *MockProductionCountryQuerier_ListProductionCountries_Call {
	_c.Call.Return(run)
	return _c
}
