// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"believer/movies/types"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRatingsQuerier creates a new instance of MockRatingsQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRatingsQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRatingsQuerier {
	mock := &MockRatingsQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRatingsQuerier is an autogenerated mock type for the RatingsQuerier type
type MockRatingsQuerier struct {
	mock.Mock
}

type MockRatingsQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRatingsQuerier) EXPECT() *MockRatingsQuerier_Expecter {
	return &MockRatingsQuerier_Expecter{mock: &_m.Mock}
}

// GetMoviesByRating provides a mock function for the type MockRatingsQuerier
func (_mock *MockRatingsQuerier) GetMoviesByRating(userID string, rating int, page int) (types.Movies, error) {
	ret := _mock.Called(userID, rating, page)

	if len(ret) == 0 {
		panic("no return value specified for GetMoviesByRating")
	}

	var r0 types.Movies
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) (types.Movies, error)); ok {
		return returnFunc(userID, rating, page)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) types.Movies); ok {
		r0 = returnFunc(userID, rating, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Movies)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(userID, rating, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRatingsQuerier_GetMoviesByRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMoviesByRating'
type MockRatingsQuerier_GetMoviesByRating_Call struct {
	*mock.Call
}

// GetMoviesByRating is a helper method to define mock.On call
//   - userID string
//   - rating int
//   - page int
func (_e *MockRatingsQuerier_Expecter) GetMoviesByRating(userID interface{}, rating interface{}, page interface{}) *MockRatingsQuerier_GetMoviesByRating_Call {
	return &MockRatingsQuerier_GetMoviesByRating_Call{Call: _e.mock.On("GetMoviesByRating", userID, rating, page)}
}

func (_c *MockRatingsQuerier_GetMoviesByRating_Call) Run(run func(userID string, rating int, page int)) *MockRatingsQuerier_GetMoviesByRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRatingsQuerier_GetMoviesByRating_Call) Return(movies types.Movies, err error) *MockRatingsQuerier_GetMoviesByRating_Call {
	_c.Call.Return(movies, err)
	return _c
}

func (_c *MockRatingsQuerier_GetMoviesByRating_Call) RunAndReturn(run func(userID string, rating int, page int) (types.Movies, error)) *MockRatingsQuerier_GetMoviesByRating_Call {
	_c.Call.Return(run)
	return _c
}
